name: mobile
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  # State & utils

  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.2.1

  # Networking
  http: ^1.4.0
  dio: ^5.4.2

  # i18n & UI
  easy_localization: ^3.0.8
  flutter_html: ^3.0.0
  intl: ^0.20.2

  # Realtime
  stomp_dart_client: ^0.4.4
  web_socket_channel: ^2.4.0

  # Media / Device
  camera: ^0.10.6
  geolocator: ^11.1.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  open_filex: ^4.4.0
  file_saver: ^0.2.7
  flutter_pdfview: ^1.3.1
  image_gallery_saver_plus: ^4.0.1



  # Sharing & Launch
  url_launcher: ^6.3.0
  share_plus: ^10.0.0

  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  path: ^1.9.0
  signature: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/en.json
    - assets/translations/vi.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
