name: mobile
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.8.1

dependencies:
    flutter:
        sdk: flutter
    provider: ^6.1.5
    signature: ^5.4.0
    flutter_dotenv: ^5.2.1
    cupertino_icons: ^1.0.8
    http: ^1.4.0
    dio: ^5.4.2
    shared_preferences: ^2.2.2
    easy_localization: ^3.0.8
    flutter_html: ^3.0.0
    stomp_dart_client: ^0.4.4
    web_socket_channel: ^2.4.0
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    intl: 0.20.2
    image_picker: ^0.8.5+3
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    flutter_launcher_icons: ^0.14.4

flutter:
    uses-material-design: true
    assets:
        - .env
        - assets/translations/en.json
        - assets/translations/vi.json

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/logo.png"
